import crafttweaker.item.IItemStack;
import mods.jei.JEI;


val Junk = [
    <minecraft:potion>.withTag({Potion: "techguns:radpotion_severe"}),
    <minecraft:potion>.withTag({Potion: "techguns:radregenerationpotion"}),
    <minecraft:splash_potion>.withTag({Potion: "techguns:radpotion_severe"}),
    <minecraft:splash_potion>.withTag({Potion: "techguns:radregenerationpotion"}),
    <minecraft:lingering_potion>.withTag({Potion: "techguns:radpotion_severe"}),
    <minecraft:lingering_potion>.withTag({Potion: "techguns:radregenerationpotion"}),
    <minecraft:tipped_arrow>.withTag({Potion: "techguns:radpotion_severe"}),
    <minecraft:tipped_arrow>.withTag({Potion: "techguns:radregenerationpotion"}),
    <techguns:bioblob:0>,
    <techguns:slimy:0>,
    <techguns:slimyladder:3>,
    <techguns:sand_hard:0>,
    <techguns:orecluster:1>,
    <techguns:orecluster:2>,
    <techguns:orecluster:3>,
    <techguns:orecluster:4>,
    <techguns:orecluster:5>,
    <techguns:orecluster:6>,
    <techguns:orecluster:7>,
    <techguns:orecluster:8>,
    <techguns:oredrill:0>,
    <techguns:oredrill:1>,
    <techguns:oredrill:2>,
    <techguns:oredrill:3>,
    <techguns:oredrill:4>,
    <techguns:oredrill:5>,
    <techguns:oredrill:6>,
    <techguns:oredrill:7>,
    <techguns:oredrill:8>,
    <techguns:itemshared:0>,
    <techguns:itemshared:25>,
    <techguns:itemshared:26>,
    <techguns:itemshared:31>,
    <techguns:itemshared:32>,
    <techguns:itemshared:43>,
    <techguns:itemshared:90>,
    <techguns:itemshared:91>,
    <techguns:itemshared:105>,
    <techguns:itemshared:134>,
    <techguns:itemshared:135>,
    <techguns:itemshared:136>,
    <techguns:itemshared:137>,
    <techguns:itemshared:138>,
    <techguns:itemshared:139>,
    <techguns:itemshared:140>,
    <techguns:itemshared:141>,
    <techguns:itemshared:142>,
    <techguns:glider>,
    <techguns:jumppack>,
    <techguns:jetpack>,
    <techguns:antigravpack>,
    <techguns:sawedoff>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:biogun>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:mibgun>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:mibgun>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:alienblaster>.withTag({ammo: 10 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:steam_boots>.withTag({power: 0}),
    <techguns:steam_leggings>.withTag({power: 0}),
    <techguns:steam_chestplate>.withTag({power: 0}),
    <techguns:steam_helmet>.withTag({power: 0}),
    <techguns:sawedoff>.withTag({ammo: 2 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:biogun>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:sawedoff>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:biogun>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:mibgun>.withTag({ammo: 0 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:mibgun>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:alienblaster>.withTag({ammo: 10 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:steam_boots>.withTag({power: 0}),
    <techguns:steam_leggings>.withTag({power: 0}),
    <techguns:steam_chestplate>.withTag({power: 0}),
    <techguns:steam_helmet>.withTag({power: 0}),
    <techguns:sawedoff>.withTag({ammo: 2 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:biogun>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}),
    <techguns:radaway>
] as IItemStack[];

for item in Junk {
    recipes.remove(item);
    JEI.removeAndHide(item);
}